version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /wgpu-testbed-webapp
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
