name: Build and Deploy Latest

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build WebApp
    steps:
     - uses: actions/checkout@v3
       with:
         submodules: true
     - name: Install Wasm-Pack
       run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
     - name: Build Wasm Project
       run: |
         cd wgpu-testbed-lib
         RUSTFLAGS=--cfg=web_sys_unstable_apis wasm-pack build
         cd ..
     - name: Build Web Project
       run: |
         cd wgpu-testbed-webapp
         yarn install
         yarn build
     - uses: actions/upload-artifact@v2
       with:
         name: webapp-build
         path: wgpu-testbed-webapp/dist

  deploy:
    if: |
      (github.event_name == 'push' 
      || (github.event_name == 'pull_request' && github.event.action != 'closed'))
       && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs: ["build"]
    name: Deploy WebApp
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: webapp-build
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_DUNE_08FACD403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "wgpu-testbed-webapp/dist" # App source code path
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_DUNE_08FACD403 }}
          action: "close"
