name: Build and Deploy Stable

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: "webapp-build"
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
  

  deploy:
    needs: ["build"]
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: "webapp-build"
      swa-api-token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_GRASS_0945F1903 }}
    secrets: inherit
    if: |
      (github.event_name == 'push' 
      || (github.event_name == 'pull_request' && github.event.action != 'closed'))
       && github.actor != 'dependabot[bot]'